# Dockerfile-primary
FROM postgres:latest

ENV POSTGRES_USER=bintang
ENV POSTGRES_PASSWORD=bintang123
ENV POSTGRES_DB=bintangdb

COPY setup-primary.sh /docker-entrypoint-initdb.d/setup-primary.sh
RUN chmod +x /docker-entrypoint-initdb.d/setup-primary.sh
