# Dockerfile-secondary
FROM postgres:latest

ENV POSTGRES_USER=bintang
ENV POSTGRES_PASSWORD=bintang123
ENV POSTGRES_DB=bintangdb

COPY setup-secondary.sh /docker-entrypoint-initdb.d/setup-secondary.sh
RUN chmod +x /docker-entrypoint-initdb.d/setup-secondary.sh
